runtime: nodejs16

instance_class: F2

env_variables: 
  BUCKET_NAME: "all-projects-ng-app-bucket"

handlers:
- url: /
  static_files: dist/all-projects/index.html
  upload: dist/all-projects/index.html

- url: /
  static_dir: dist/all-projects 